---
AWSTemplateFormatVersion: 2010-09-09
Description: Create bastion
Parameters:
    # General
        VPCName:
            Description: Environment to use
            Type: String
            Default: Dev
            AllowedValues:
                - Dev
                - QA
                - Production



Resources:
    #TODO
Outputs:
